### PR TITLE
add pumpfun to realtime

### PR DESCRIPTION
**Pull request by tarikceric**
Add Pumpfun logs to requests for logs decoder

- DML to remove events from silver.decoded_instructions_combined and silver.decoded_instructions (`withdraw` events are the only ones without 'logs' so excluded those)

```
delete from solana.silver.decoded_instructions_combined
where program_id = '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P'
and (event_type <> 'withdraw' or event_type is null)
and inner_index is not null;

delete from solana.silver.decoded_instructions 
where program_id = '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P'
and (decoded_instruction:name::string <> 'withdraw' or decoded_instruction:error is not null)
and inner_index is not null;
```

- Command to run backfill for last two days
`dbt run-operation decoded_logs_backfill_generate_views --args '{"program_id": "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P", "start_date": "2024-08-11", "end_date": "2024-08-13"}' -t prod`

### CODE REVIEW

**Comment by desmond-hui** [comment]
> ```
> delete from solana.silver.decoded_instructions_combined
> where program_id = '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P'
> and (event_type <> 'withdraw' or event_type is null);
> 
> delete from solana.silver.decoded_instructions 
> where program_id = '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P'
> and (decoded_instruction:name::string <> 'withdraw' or decoded_instruction:error is not null);
> ```

Add `inner_index IS NOT NULL` condition as a sanity check to ensure we are only removing inner instructions since trade logs cannot occur as a top level instruction

**Comment by desmond-hui** [comment]
Before merging, also run the backfill for the last 2 days so the realtime pipeline has less work to do when it is turned on. Put the backfill `dbt run-operations` command here for a sanity check

**Review by desmond-hui — CHANGES_REQUESTED** [review]
See above comments

**Comment by tarikceric** [comment]
> See above comments

updated delete queries and added backfill command

**Review by desmond-hui — APPROVED** [review]

**Comment by tarikceric** [comment]
update: 2 day backfill complete, and ran delete DML

**Pull request merged**
